let tiendashampooItemsData = [
    {
      id: "Revitalizante1",
      nombre: "Revitalizante",
      opciones: "Presentaciones",
      gramaje: 50,
      precio: 48,
      gramaje1: 100,
      precio1: 98,
      ingredientes: "Extracto de avena • Inulina <br> Aceite de avellana • Hibiscus(jamaica)",
      descripcion: "Para: TODO TIPO DE PELO, ESPECIALMENTE NORMAL Y MIXTO. <br> Vas a sentir como tu cabello vuelve a la vida, el nombre le hace total justicia.",
      cant: "Cantidad",
      img: "./Imagenes/Catalogo/Shampoo-Revitalizante.jpg",
    },
    {
      id: "LavandaRomero1",
      nombre: "Lavanda y Romero",
      opciones: "Presentaciones",
      gramaje: 50,
      precio: 48,
      gramaje1: 100,
      precio1: 98,
      ingredientes: "Extracto de lavanda • Arcilla verde <br> Romero • Aceite de semilla de uva",
      descripcion: "Ideal para TODO TIPO DE PELO. <br> Perfecto para cuero cabelludo: GRASO, con caspa, barritos, comezón, psoriasis. <br> Seborregulador, controla la caída, controla la caspa, estimula el crecimiento, reparador, antifrizz, hidratante, antiséptico, antiinflamatorio. <br> ¡Nuestro favorito, es perfecto!",
      cant: "Cantidad",
      img: "./Imagenes/Catalogo/Shampoo-Lavanda-Romero.jpg",
    },
    {
      id: "AvenaCoco1",
      nombre: "Avena y Coco",
      opciones: "Presentaciones",
      gramaje: 50,
      precio: 48,
      gramaje1: 100,
      precio1: 98,
      ingredientes: "Avena • Olivo <br> Aceite de coco",
      descripcion: "Ideal para CUERO CABELLUDO NORMAL y SECO. <br> Hidrata, fortalece el cabello quebradizo, aporta brillo, estimula el crecimiento, antioxidante. <br> ¡Vas a amar el cambio inmediato que sentirás en tu pelo con nuestra fórmula buenísima para cabello normal!",
      cant: "Cantidad",
      img: "./Imagenes/Catalogo/Shampoo-Avena-y-Coco.jpg",
    },
    {
      id: "ControlCaida1",
      nombre: "Control Caída",
      opciones: "Presentaciones",
      gramaje: 50,
      precio: 48,
      gramaje1: 100,
      precio1: 98,
      ingredientes: "Extracto de fenogreco • Levadura de cerveza <br> Aceite de ricino • Alga espirulina • Té verde",
      descripcion: "Ideal para TODO TIPO DE PELO. <br> Cada ingrediente es perfecto para frenar la caída y nutrir tu cabello.",
      cant: "Cantidad",
      img: "./Imagenes/Catalogo/Shampoo-Control-Caida-2.jpg",
    },
    {
      id: "MangoAloe1",
      nombre: "Mango y Aloe",
      opciones: "Presentaciones",
      gramaje: 50,
      precio: 48,
      gramaje1: 100,
      precio1: 98,
      ingredientes: "Queratina • Aloe vera <br> Manteca de mango",
      descripcion: "Para todo tipo de cabello, pero ideal para CUERO CABELLUDO SECO. <br> Ayuda a controlar la caspa. <br> Fuerza, brillo, suavidad, repara, nutre, aporta flexibilidad, antifrizz, calmante. <br> Olvídate de la comezón causada por la resequedad del cuero cabelludo y del molesto polvito blanco en tu ropa, es una fórmula súper hidratante.",
      cant: "Cantidad",
      img: "./Imagenes/Catalogo/Shampoo-Mango-Aloe.jpg",
    },
  ];